[trident_incidents]
homePath = $SPLUNK_DB/trident_incidents/db
coldPath = $SPLUNK_DB/trident_incidents/colddb
thawedPath = $SPLUNK_DB/trident_incidents/thaweddb
maxDataSize = 5000

[trident_audit]
homePath = $SPLUNK_DB/trident_audit/db
coldPath = $SPLUNK_DB/trident_audit/colddb
thawedPath = $SPLUNK_DB/trident_audit/thaweddb
maxDataSize = 1000
