[trident_incident_collector]
disabled = false
index = trident_incidents
sourcetype = trident:incident
token = trident-hec-token

[trident_audit_collector]
disabled = false
index = trident_audit
sourcetype = trident:audit
token = trident-audit-hec-token
