[trident:incident]
DATETIME_CONFIG = CURRENT
KV_MODE = json
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%6NZ
TIME_PREFIX = "timestamp"\s*:\s*"
MAX_TIMESTAMP_LOOKAHEAD = 40
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
TRUNCATE = 0

[trident:audit]
DATETIME_CONFIG = CURRENT
KV_MODE = json
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%6NZ
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)

[trident:metrics]
DATETIME_CONFIG = CURRENT
KV_MODE = json
TIME_FORMAT = %Y-%m-%dT%H:%M:%SZ
TIME_PREFIX = "time"\s*:\s*"
SHOULD_LINEMERGE = false
